### ISSUE TITLE
Fix package / import structure

### ISSUE THREAD

**Issue by jessemortenson** [openstates/scrapy-test#1]
We should be able to run scrapers using the scrapy crawl command, eg:

`poetry run scrapy crawl nv-bills -a session=2023Special35 -O nv-bills-scout.json -s "ITEM_PIPELINES={}"`

or even

`poetry run python -m scrapy.cmdline crawl nv-bills -a session=2023Special35 -O nv-bills-scout.json -s "ITEM_PIPELINES={}"`

however right now both of these, for me, result in:

```
...
File "/home/jesse/repo/openstates/scrapy-test/scrapers/scrapers/spiders/nv-bills.py", line 6, in <module>
    from core.scrape import Bill
ModuleNotFoundError: No module named 'core'
```

Basically I am getting the problem [described here](https://stackoverflow.com/questions/56102040/how-to-import-my-own-modules-into-a-scrapy-project) which is similar to [this linked issue](https://stackoverflow.com/questions/36701958/importing-modules-from-a-neighbouring-folder-in-python)

I can resolve this on my machine by setting the project root as part of `PYTHONPATH`, but shouldn't need to: `export PYTHONPATH='/home/jesse/repo/openstates/scrapy-test:/home/jesse/.cache/pypoetry/virtualenvs/scrapy-test-vH1KNbGC-py3.9/lib/python3.9/site-packages`

**Comment by braykuka** [comment]
@jessemortenson 
There are 2 ways to solve this issue.
1.  The current directory structure is scrapers/scrapers/.... We can move child `scrapers` folder to the parent.
2. Another way is to make `core` as package using poetry. 

Please let me know your opinion.

**Comment by jessemortenson** [comment]
I think option 1 is totally fine.

There is currently a blocker to making the `core` package a standalone dependency: we actually already have a separate package, which is https://github.com/openstates/openstates-core / https://pypi.org/project/openstates/. But that `openstates` package (which contains the code currently in the `core` folder you mention) depends on a package called `spatula` which in turn has a dependency on a version of `attrs` which appears to be in conflict with `scrapy`
